export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const ONDARKMODE = "ONDARKMODE";
export const OFFDARKMODE = "OFFDARKMODE";

export const SETLOCATIONS = "SETLOCATIONS";
export const ADDLOCATION = "ADDLOCATION";
export const EDITLOCATION = "EDITLOCATION";
export const DELETELOCATION = "DELETELOCATION";

export const SETFLIGHTS = "SETFLIGHTS";
export const ADDFLIGHT = "ADDFLIGHTS";
export const MANYFLIGHTS = "MANYFLIGHTS";
export const EDITFLIGHT = "EDITFLIGHTS";
export const DELETEFLIGHT = "DELETEFLIGHTS";

export const SETONLINE = "SETONLINE";

export const SETAIRMEN = "SETAIRMEN";
export const APPROVEAIRMAN = "APPROVEAIRMAN";
export const EDITAIRMAN = "EDITAIRMAN";
export const SETPENDING = "SETPENDING";

export const SETAIRCRAFTS = "SETAIRCRAFTS";
export const ADDAIRCRAFT = "ADDAIRCRAFT";
export const EDITAIRCRAFT = "EDITAIRCRAFT";
export const DELETEAIRCRAFT = "DELETEAIRCRAFT";

export const SETCREWPOSITION = "SETCREWPOSITION";
export const SETRANKS = "SETRANKS";
export const SETMETAPOSITIONS = "SETMETAPOSITIONS";

export const SETAIRCRAFTSTATUS = "SETAIRCRAFTSTATUS";
export const SETUSERSTATUS = "SETUSERSTATUS";

export const SETSCHEDULE = "SETSCHEDULE";

export const SETAIRCRAFTMODELS = "SETAIRCRAFTMODELS";
export const ADDAIRCRAFTMODEL = "ADDAIRCRAFTMODEL";
export const EDITAIRCRAFTMODEL = "EDITAIRCRAFTMODEL";
export const DELETEAIRCRAFTMODEL = "DELETEAIRCRAFTMODEL";

export const COMMITSCHEDULE = "COMMITSCHEDULE";