export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const GOTINITIALESSENTIALREQUEST = "GOTINITIALESSENTIALREQUEST";
export const ONDARKMODE = "ONDARKMODE";
export const OFFDARKMODE = "OFFDARKMODE";

export const SETAIRMEN = "SETAIRMEN";
export const SETAIRCRAFTMODELS = "SETAIRCRAFTMODELS";
export const SETLOCATIONS = "SETLOCATIONS";
export const SETAIRCRAFTS = "SETAIRCRAFTS";
export const SETFLIGHTS = "SETFLIGHTS";
export const SETCREWPOSITION = "SETCREWPOSITION";
export const SETRANKS = "SETRANKS";

export const SETAIRCRAFTSTATUS = "SETAIRCRAFTSTATUS";
export const SETUSERSTATUS = "SETUSERSTATUS";

export const SETWEBSOCKET = "SETWEBSOCKET";
