export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const ONDARKMODE = "ONDARKMODE";
export const OFFDARKMODE = "OFFDARKMODE";

export const SETLOCATIONS = "SETLOCATIONS";
export const ADDLOCATION = "ADDLOCATION";
export const EDITLOCATION = "EDITLOCATION";
export const DELETELOCATION = "DELETELOCATION";

export const SETFLIGHTS = "SETFLIGHTS";
export const ADDFLIGHT = "ADDFLIGHTS";
export const EDITFLIGHT = "EDITFLIGHTS";
export const DELETEFLIGHT = "DELETEFLIGHTS";

export const SETONLINE = "SETONLINE";

export const SETAIRMEN = "SETAIRMEN";
export const APPROVEAIRMAN = "APPROVEAIRMAN";
export const EDITAIRMAN = "EDITAIRMAN";
export const SETAIRCRAFTMODELS = "SETAIRCRAFTMODELS";
export const SETPENDING = "SETPENDING";

export const SETAIRCRAFTS = "SETAIRCRAFTS";

export const SETCREWPOSITION = "SETCREWPOSITION";
export const SETRANKS = "SETRANKS";

export const SETAIRCRAFTSTATUS = "SETAIRCRAFTSTATUS";
export const SETUSERSTATUS = "SETUSERSTATUS";

export const SETSCHEDULE = "SETSCHEDULE";
export const COMMITSCHEDULE = "COMMITSCHEDULE";
